//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 02 16:33:04 PDT 2006
//----------------------------------------------------

package edu.ucsc.neurobiology.vision.math.expressions;

/** CUP generated class containing symbol constants. */
public class ExpressionParserSymbols {
    /* terminals */
    public static final int POW = 8;
    public static final int ABS = 35;
    public static final int UMINUS = 9;
    public static final int PI = 24;
    public static final int FFT = 44;
    public static final int NOT_EQUAL = 19;
    public static final int LPAREN = 10;
    public static final int GREATER = 16;
    public static final int LESS = 14;
    public static final int E = 25;
    public static final int D = 46;
    public static final int RPAREN = 11;
    public static final int NORM = 42;
    public static final int NOT = 20;
    public static final int AND = 21;
    public static final int OR = 22;
    public static final int COMMA = 2;
    public static final int LN = 33;
    public static final int DIV = 6;
    public static final int EXTREME = 41;
    public static final int LESS_EQUAL = 15;
    public static final int MIN = 39;
    public static final int EXP = 32;
    public static final int EOF = 0;
    public static final int EQUAL = 18;
    public static final int TRUE = 26;
    public static final int GREATER_EQUAL = 17;
    public static final int error = 1;
    public static final int MUL = 5;
    public static final int ADD = 3;
    public static final int JOIN = 45;
    public static final int MEAN = 37;
    public static final int NUMBER = 23;
    public static final int COS = 31;
    public static final int MOD = 7;
    public static final int NORMRMS = 43;
    public static final int LBRACK = 12;
    public static final int SIN = 30;
    public static final int RBRACK = 13;
    public static final int SUM = 36;
    public static final int STRING = 29;
    public static final int FALSE = 27;
    public static final int LOG10 = 34;
    public static final int MAX = 40;
    public static final int SUB = 4;
    public static final int RAD_NORM = 38;
    public static final int IDENTIFIER = 28;
}
